# Generated by Django 3.1.5 on 2021-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('net_price', models.FloatField()),
                ('tax', models.FloatField(default=5.0)),
                ('gross_price', models.FloatField()),
            ],
            options={
                'verbose_name': 'shoe',
                'verbose_name_plural': 'shoes',
                'ordering': ['-gross_price'],
            },
        ),
    ]
