# Generated by Django 3.1.5 on 2021-02-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoes',
            options={'ordering': ['-brand'], 'verbose_name': 'shoe', 'verbose_name_plural': 'shoes'},
        ),
        migrations.AlterField(
            model_name='shoes',
            name='gross_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='net_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
